Tribute page modification
sheldonwafula/Tribute-Page pull request #1
Opened 2023-01-23 12:18 UTC by sheldonwafula

In this pull request:
-I have created a tribute page with HTML.
-I have added CSS for styling.
-I have added a descriptive readme file.
-I have fixed all linter errors.

2023-01-23 12:33 UTC, sheldonwafula commented
1. The project works properly.
2. No linters errors.
3. Correct flow used.
4. well-documented repository.

2023-01-23 12:37 UTC, sheldonwafula commented
I think it would be better to align the button properly. Reducing the left margin to align with the rest of the content.

2023-01-23 12:41 UTC, sheldonwafula commented
I think it would be better to align the heading at the center  <h1 id="title">Nelson Mandela</h1>.

2023-01-23 13:06 UTC, didierganthier requested changes
Hi @sheldonwafula ,

🎉 Good job so far! You're making significant progress on this project, but there are still a few areas that need attention before we can move on to the next step.

<img src="https://media.giphy.com/media/cLwDB2j2a7JFdzQzYu/giphy.gif" />

## Highlights
- Used bullet points ✔️ 

## Required Changes 🛠
- [ ] Great job on the comments you made 👍🏽 but in order to improve the review and make it look better, you should consider using the "Review changes" feature from GitHub. It makes it easier to "Comment", "Approve" or "Request Changes". In order to do that you can follow these steps:
1. Files changed 
![Screenshot 2023-01-23 at 07 57 28](https://user-images.githubusercontent.com/45739963/214045442-60701030-e3b3-4c67-91e5-c2c869a8e550.png)
2. Review changes
![Screenshot 2023-01-23 at 07 57 47](https://user-images.githubusercontent.com/45739963/214045506-18c89bbf-bf3a-4438-aaf6-ad3b8cd6a6fa.png)
3. Write your review (in markdown format)
![Screenshot 2023-01-23 at 07 58 23](https://user-images.githubusercontent.com/45739963/214045620-74900d00-007c-4f2a-ae61-e2198300c1d9.png)
4. Comment, Approve or Request changes
![Screenshot 2023-01-23 at 07 59 38](https://user-images.githubusercontent.com/45739963/214045837-b3a449dd-d560-4d1b-a641-8d51fa1d59dc.png)
5. Submit review
![Screenshot 2023-01-23 at 08 00 02](https://user-images.githubusercontent.com/45739963/214045912-ff845b30-f8d6-4084-a99e-85d90c86a47b.png)

- [ ] To make this even better 😉 make sure you also use inline comments as requested for this project 💭 inline comments help the student understand exactly what part of the code you're commenting about. See below for an example 👇🏽 

- Please review the comments under the review for specific changes that still need to be made.

## Optional Suggestions 💡
- While these comments with the [OPTIONAL] prefix won't prevent the approval of this pull request, I strongly recommend taking them into account as they can improve your code.

🚀 Keep pushing forward, you're almost there! If you have any questions or need clarification on anything, feel free to leave a comment in the pull request thread and don't forget to tag me so I'll receive the notification.

**Please note**
- To avoid confusion and delays, please do not open a new pull request for re-reviews. Use the same pull request submitted for the first review, unless otherwise instructed.

------
As per the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561), you have a limited number of reviews per project. If you feel that the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s). 

Cheers and happy coding! 👏👏👏

2023-01-23 13:06 UTC, didierganthier commented on index.html
> +        </div>
For example, this is an inline comment 🙂 from lines `17` to `20`, it appears below the review. Also make sure that when you add one, you click on `Start a review` and not `Add single comment`. The difference? 🤔 If you click on `Add single comment`, the comment will appear before the review and seem unrelated to it, but if you click on `Start a review`, it only gets posted once you submit the review and appears below it. I hope this helps, let me know if you have any questions ❓ 😉

2023-01-24 09:01 UTC, sheldonwafula reviewed
- I think it would be better to align the heading at the center.
 ![Screenshot 2023-01-24 115328](https://user-images.githubusercontent.com/108523641/214249026-e605b18d-60af-4098-824a-fff5f05e5f70.png)
- I think it would be better to align the button properly. Reducing the left margin to align with the rest of the content.
 ![Screenshot 2023-01-24 115842](https://user-images.githubusercontent.com/108523641/214249983-f82241af-93ea-453e-ad73-89be2c2f9aa8.png)

2023-01-24 09:16 UTC, sheldonwafula reviewed
Please add .LICENSE to your README file. Your readme appears to have no license details.
![Screenshot 2023-01-24 121524](https://user-images.githubusercontent.com/108523641/214253396-8122630a-0ff6-45dd-be8f-d0a573e12ba3.png)

2023-01-24 09:33 UTC, Shedrack-Sunday requested changes
Hi @sheldonwafula     👋 

# CHANGES REQUIRED ♻️

Great work on the project 👏
I notice you did make efforts as regards suggestions made by the previous reviewer to use inline comments, However, you still need to work on that to move to the next project. 💯 
![](https://user-images.githubusercontent.com/80612925/157397398-00904e26-60ec-46cd-9510-240661c250ef.gif)


Highlights
✅All linters are checked
✅ Descriptive commit messages 


Required Changes ♻️

- [ ] What you appeared to have done, is take a screenshot of changes you suggested based on the review task however, the guide to make incline comments is different. [This link ](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/code-review/articles/give_code_review_basics.md) has a step-by-step guide on how to do that. please kindly revisit it to see the workflow 👍 
## Vidoe link for inline comment sample 
[Video link](https://www.loom.com/share/e847c46aa4814534b23b3a8e4dd60d6d)

_check the comment section for a detailed review_

Optional suggestions
Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application.


Cheers and Happy coding!👏👏👏
Feel free to leave any questions or comments in the PR thread if something is not 100% clear, and please remember to tag me in your question so I can receive the notification.


Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.

As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2023-01-24 09:36 UTC, Shedrack-Sunday commented
- [ ] You're not meant to use a snapshot. I've taken a screenshot of the process phase and attached links and video path to help you see how its done in my review below 

## Expected process :
![image](https://user-images.githubusercontent.com/50990925/214257586-fca2a267-7c04-407d-a74e-7c0b3a6007ef.png)

2023-01-24 10:18 UTC, sheldonwafula reviewed
CHANGES REQUIRED.
Please make the changes and  If you have any questions or need clarification on anything, feel free to leave a comment in the pull request thread and don't forget to tag me so I'll receive the notification.

2023-01-24 10:18 UTC, sheldonwafula commented on index.html
> +        <h1 id="title">Nelson Mandela</h1>
I think it would be better to align the heading at the center,to make your page look better.

2023-01-24 10:18 UTC, sheldonwafula commented on README.md
> +This project is [MIT](./LICENSE) licensed.
Please add .LICENSE to your README file. Your readme appears to have no license details.

2023-01-24 10:18 UTC, sheldonwafula commented on index.html
> +            <a class="info" href="https://en.wikipedia.org/wiki/Nelson_Mandela" target="_blank">Read More about our hero Nelson Mandela</a>
I think it would be better to align the button properly. Reducing the left margin to align with the rest of the content.

2023-01-24 10:22 UTC, IngDavidTM approved these changes
Hi <STUDENT_NAME> 🙋‍♂️, 

# ✔️   Status: APPROVED 🏆 🎉 🎊 

You have done a great job on this project, keep it up 👍 🥇. Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations!  🎉💯🌟 

## Top highlight 🎯

- The review uses inline comments ✅ 
<img src="https://media3.giphy.com/media/xT0xezQGU5xCDJuCPe/giphy.gif"/>

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-24 11:09 UTC, merged